<?php

declare(strict_types=1);

return [
    'directories' => [
        '.build',
        '.claude',
        '.codegraph',
        '.ddev',
        '.git',
        '.github',
        'bin',
        'build',
        'config',
        'Documentation-GENERATED-temp',
        'MEMORY',
        'Plans',
        'public',
        'tailor-version-upload',
        'Tests',
        'var',
        'vendor',
    ],
    'files' => [
        'DS_Store',
        'CLAUDE.md',
        'codecov.yml',
        'CONTRIBUTING.md',
        'editorconfig',
        'esbuild.config.mjs',
        'gitattributes',
        'gitignore',
        'package.json',
        'package-lock.json',
        'packaging_exclude.php',
        'php-cs-fixer.php',
        'phpstan.neon',
        'phpstan-baseline.neon',
        'phpunit.xml',
        'rector.php',
        'renovate.json',
        'SECURITY.md',
        'spectral.yaml',
    ],
];
