services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  MaikSchneider\TcaApi\:
    resource: '../Classes/*'

  MaikSchneider\TcaApi\Security\TableAccessControl:
    arguments:
      $allowList: []
      $denyList: []

  MaikSchneider\TcaApi\Serializer\Processing\TypoLinkProcessor:
    public: true

  MaikSchneider\TcaApi\Testing\EventCollector:
    public: true
    tags:
      - name: event.listener
        event: MaikSchneider\TcaApi\Event\BeforeWriteEvent
        method: onBeforeWrite
      - name: event.listener
        event: MaikSchneider\TcaApi\Event\AfterWriteEvent
        method: onAfterWrite
      - name: event.listener
        event: MaikSchneider\TcaApi\Event\BeforeOperationEvent
        method: onBeforeOperation
      - name: event.listener
        event: MaikSchneider\TcaApi\Event\AfterOperationEvent
        method: onAfterOperation
